language: cpp
compiler:
  - gcc
  - clang

script:
  - cmake .
  - make

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libqt4-dev libsqlite3-dev

matrix:
  fast_finish: true
